### ISSUE TITLE
[Failed-AutoCherryPick] - Pagination refactor

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/airgun#1032]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/airgun/actions/runs/6815653976)
- [Parent Pull Request](https://github.com/SatelliteQE/airgun/pull/947)

**Comment by mstrlc** [comment]
Cherrypicked https://github.com/SatelliteQE/airgun/pull/1036
