### ISSUE TITLE
Create Red Hat Repo Dropdown Widgets 

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/airgun#110]
We need a widget for the Red Hat repos dropdown 
<img width="919" alt="screen shot 2018-06-15 at 10 13 05 am" src="https://user-images.githubusercontent.com/1334675/41472598-f1f6b0b4-7084-11e8-867c-b6d31161c8eb.png">

**Comment by mirzal** [comment]
Today, we have https://github.com/SatelliteQE/airgun/blob/master/airgun/entities/redhat_repository.py and couple of tests in https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_repository.py that make use of it.

If there is still something specific for us to work on, feel free to re-open the issue and provide more details.
