### ISSUE TITLE
Cover Discovery Rules entity

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#118]
* [x] All entities page
![image](https://user-images.githubusercontent.com/10895065/42322454-492a9194-8065-11e8-9a0e-c8cd8f8c85b0.png)

* [x] Create/Edit entity page
![image](https://user-images.githubusercontent.com/10895065/42282131-2ee728ea-7fae-11e8-9719-b6fc003ad670.png)

* [ ] Correct Discovered Hosts redirection
![image](https://user-images.githubusercontent.com/10895065/42322534-90eb9960-8065-11e8-9eab-fe885287d639.png)
* [ ] Correct Hosts redirection and search
![image](https://user-images.githubusercontent.com/10895065/42322568-b18024e8-8065-11e8-820c-c506fcf2192b.png)
* [x] Disable/Delete actions

**Comment by tstrych** [comment]
Do I continue with this entity when you change labels ? 

1. How I should compare the results if there is no search filter, and how than read the structures to compare results. What i should use ?
2. What I should write to breadcrumb when there is no writen where I am, there still just title Discovery Rules, nothing is changing
3. Which Widget should be used for Search attribute in create rules ?
4. Which widget I should use for Host_limit and Priority there is just LimitInput but these don't have any conditionals, or just text input ?
I tried to write LimitInput without conditionals into widgets.py, but it doesn't work, when you look at it can you tell me why ?
```class LimitInputNoConditionals(GenericLocatorWidget):
    text_value = Text(".")

    def __init__(self, parent, id=None, locator=None, logger=None):
        """Supports initialization via ``locator=`` or ``id=``"""
        if locator and id or not locator and not id:
            raise TypeError('Please specify either locator or id')
        locator = locator or ".//input[@id='{}']".format(id)
        super(LimitInputNoConditionals, self).__init__(
            parent, locator=locator, logger=logger)

    def fill(self, value):
        return self.text_value.fill(value)

    def read(self):
        return self.text_value.read()```

**Comment by ldjebran** [comment]
Correct Discovered Hosts redirection
Correct Hosts redirection and search

depend from https://github.com/SatelliteQE/airgun/pull/202
