### ISSUE TITLE
Cover Host Collections

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#136]
Hosts -> Host Collections

* [x] All entities page
* [x] Create entity
* [ ] Edit page - Details tab (Partially done)
* [x] Edit page - Hosts
* [ ] Edit page - Package Installation, Removal, and Update
* [ ] Edit page - Errata Installation
* [ ] Edit page - Change assigned Lifecycle Environment or Content View

**Comment by abalakh** [comment]
Not required for GA (no t2/t3 tests):
* [ ] Edit page - Host Collection Membership
* [ ] Edit page - Subscription Management
* [ ] Edit page - Create copy
