### ISSUE TITLE
Views: Hosts entity

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#138]
Location:
Content -> All hosts

Views:
* [x] Hosts list
* [x] Hosts list - Actions - Change Group
* [x] Hosts list - Actions - Change Environment
* [x] Hosts list - Actions - Assign to Organization
* [x] Hosts list - Actions - Assign Compliance Policy
* [x] Host Create - Host tab
* [x] Host Create - Ansible Roles tab
* [x] Host Create - Operating System tab
* [x] Host Create - Interfaces tab
* [x] Host Create - Interfaces - Create/Edit Interface
* [ ] Host Create - Parameters tab
* [x] Host Create - Additional Information tab
* [x] Host Details
* [x] Host Details - Properties tab
* [x] Host Edit (similar to Create)

**Comment by abalakh** [comment]
Not required for GA (no t2/t3 tests):
* [ ] Hosts list - Actions - Build Hosts
* [ ] Hosts list - Actions - Edit Parameters
* [ ] Hosts list - Actions - Disable Notifications
* [ ] Hosts list - Actions - Enable Notifications
* [ ] Hosts list - Actions - Disassociate Hosts
* [ ] Hosts list - Actions - Rebuild Config
* [ ] Hosts list - Actions - Assign to Location
* [ ] Hosts list - Actions - Change Owner
* [ ] Hosts list - Actions - Change Puppet Master
* [ ] Hosts list - Actions - Change Puppet CA
* [ ] Hosts list - Actions - Change Power State
* [ ] Hosts list - Actions - Delete Hosts
* [ ] Hosts list - Actions - Unassign Compliance Policy
* [ ] Hosts list - Actions - Change OpenSCAP Capsule
* [ ] Host Create - Puppet Classes tab
* [ ] Host Details - Metrics tab
* [ ] Host Details - Templates tab
* [ ] Host Details - NICs tab
* [ ] Host Details - Audits
* [ ] Host Details - Build
* [ ] Host Clone (similar to Edit)

**Comment by oshtaier** [comment]
Blocked by https://github.com/RedHatQE/widgetastic.core/issues/106
