### ISSUE TITLE
Update widgets and views according to satellite 6.4 changes

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#14]
As per @omaciel request, we should develop against sat6.4. At least navigation menu differs there, we should update it (and all the rest discovered places).

**Comment by abalakh** [comment]
@omaciel btw, should we support 6.4 only or should we retain backwards compatibility as well?
Widgetastic supports version picking, but that's definitely some extra effort we should be aware off before introducing changes.

**Comment by omaciel** [comment]
@abalakh let's look at 6.4 and beyond. For 6.3 we will run Robottelo's UI tests

**Comment by mfalesni** [comment]
And I am noting that I should be looking at the vertical menu compatibility.

**Comment by abalakh** [comment]
@oshtaier what's the status of this issue? Can we close it, had #29 resolved it?

**Comment by oshtaier** [comment]
Yeah, as we do not have many views or widgets - it was easy
