### ISSUE TITLE
Cover Provisioning Template views

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#140]
Hosts -> Provisioning Template

* [x] All entities view
![image](https://user-images.githubusercontent.com/10895065/42465329-557782d4-83b4-11e8-8350-5094c22eebd6.png)
* [x] Create/Edit navigation
* [x] Details - Template
* [x] Details - Type
* [x] Details - Locations
* [x] Details - Organizations
* [x] Details - Help (out of scope of test automation)
* [x] Clone entity

**Comment by abalakh** [comment]
Not required for GA (no t2/t3 tests):
* [ ] Details - Association
* [ ] Details - History
* [ ] Build PXE Default action
