### ISSUE TITLE
[Failed-AutoCherryPick] - [6.15.z] browser teardown fix at session exit

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/airgun#1416]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.16.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/airgun/actions/runs/9353216211)
- [Parent Pull Request](https://github.com/SatelliteQE/airgun/pull/1413)

**Comment by pnovotny** [comment]
Closing, as changes for 6.16 should currently be pushed to master branch.
