### ISSUE TITLE
Cover Policies functionality

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#144]
Hosts -> Policies

* [ ] All entities page
![image](https://user-images.githubusercontent.com/10895065/42471144-58f4edc8-83c5-11e8-8ce1-3657fbcbacc4.png)
* [ ] Create/Edit navigation
* [ ] Details - Create Policy
![image](https://user-images.githubusercontent.com/10895065/42470873-7e68b3ec-83c4-11e8-8f4f-450e9906fd4d.png)
* [ ] Details - SCAP content
![image](https://user-images.githubusercontent.com/10895065/42470900-91c7af06-83c4-11e8-8435-64034cd446ef.png)
* [ ] Details - Schedule
![image](https://user-images.githubusercontent.com/10895065/42470919-a55a0f5a-83c4-11e8-86f8-6bd0327b7034.png)
* [ ] Details - Locations
![image](https://user-images.githubusercontent.com/10895065/42471006-eecd1e3e-83c4-11e8-9fa6-c6381589811c.png)
* [ ] Details - Organizations
![image](https://user-images.githubusercontent.com/10895065/42471049-11bee5ee-83c5-11e8-9e7f-4bd91db0d8f4.png)
* [ ] Details - Host Groups
![image](https://user-images.githubusercontent.com/10895065/42471074-25d2db8a-83c5-11e8-8c2c-a6c8bcbf99e3.png)

**Comment by abalakh** [comment]
Closed via #201
