### ISSUE TITLE
[Failed-AutoCherryPick] - removed (.) which fails to navigate to host

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/airgun#1466]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.15.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/airgun/actions/runs/9937111657)
- [Parent Pull Request](https://github.com/SatelliteQE/airgun/pull/1461)

**Comment by amolpati30** [comment]
"trigger": "test-robottelo"
"pytest": "-k 'test_positive_non_admin_user_access_with_usergroup' tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt"
"airgun": "15489"

**Comment by amolpati30** [comment]
PR - https://github.com/SatelliteQE/airgun/pull/1453
Above Pr is already raised but still changes has not been merged in cherry_pick 6.15.
So closing this issue which is not valid here.
