### ISSUE TITLE
[Failed-AutoCherryPick] - removed (.) which fails to navigate to host

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/airgun#1467]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.14.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/airgun/actions/runs/9937111657)
- [Parent Pull Request](https://github.com/SatelliteQE/airgun/pull/1461)

**Comment by amolpati30** [comment]
Fix is already present, so closing this task
