### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#15]
This task consists of following subtasks:

- [x] Create `docs/` dir, install sphinx there
- [x] Configure sphinx' `conf.py`
- [x] Add rst files for all the modules
- [x] Introduce travis check of documentation errors
- [x] Publish docs to readthedocs.org

**Comment by jhutar** [comment]
<abalakht> jhutar: take a look at https://github.com/SatelliteQE/robottelo/tree/master/docs and https://github.com/SatelliteQE/nailgun/tree/master/docs then
<abalakht> both projects have sphinx installed and properly configured with everything generated and published. those are nice examples

**Comment by jhutar** [comment]
Hello. What is meant by "check of documentation errors"? Would that be a spell check on *.rst files? Or building a docs in Travis with Sphinx and checking it built correctly?

**Comment by abalakh** [comment]
>Or building a docs in Travis with Sphinx and checking it built correctly
This. Also make sure to use "nitpicky mode" and "treat warnings like errors" flags.

**Comment by abalakh** [comment]
And you should use autodocs to generate docs from docstrings. Basically the idea of extra travis check is to validate our docstrings.

**Comment by omaciel** [comment]
By the way Jeremy Audet has a ton of experience with Sphinx and "linting" documentation :)

**Comment by jhutar** [comment]
To finish last piece of this, "Publish docs to readthedocs.org", we need account at ReadTheDocs. I have no problem creating one myself, but do we have some shared account for all the SatelliteQE projects there? Any idea @omaciel?

https://docs.readthedocs.io/en/latest/getting_started.html#sign-up-and-connect-an-external-account

**Comment by omaciel** [comment]
@jhutar just added the hook for it but I can't remember what credentials we use for this :) Let me try to refresh my memory

**Comment by omaciel** [comment]
@jhutar I think I got it but I am seeing a message telling me that the webhook may not be correct.

https://readthedocs.org/projects/airgun/

![screen shot 2018-02-28 at 7 03 38 pm](https://user-images.githubusercontent.com/53362/36820073-22c3be22-1cba-11e8-92f0-32946536cc25.png)

**Comment by jhutar** [comment]
Thank you @omaciel .

I have found this docs on how to setup Github repo webhook for ReadTheDocs:

http://docs.readthedocs.io/en/latest/webhooks.html#github

And possibly another issue looking into Builds:

https://readthedocs.org/projects/airgun/builds/

it fails when it is running `pip install -r requirements.txt`. Or maybe the problem is that it uses python2.7?

This is how to build the docs:

https://github.com/SatelliteQE/airgun/blob/master/docs/build-docs.rst

Could you please take a look or give me access to both ReadTheDocs and this repo admin?

**Comment by elyezer** [comment]
In the rear the docs project settings you can set if you wanna build using Python 2 or 3. Maybe worth trying changing that and checking if it would fix the issue.

**Comment by omaciel** [comment]
Changed project to use Python 3 and boom! Works! https://airgun.readthedocs.io/en/latest/

Thanks @elyezer !!!  Also, adding Jan Hutar to RTD ownership.

**Comment by jhutar** [comment]
Magick. Works now. Created #38 to track almost empty API -> Entities and API -> Views (seems good in local docs build).
