### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Unexpected server error.

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/airgun#191]
See `https://<jenkins>/view/Satellite6.4/job/automation-6.4-tier2-rhel7/40/testReport/tests.foreman.ui_airgun/test_user/test_positive_create_with_all_roles/`

```
        with session:
            session.user.create({
                'user.login': name,
                'user.auth': 'INTERNAL',
                'user.password': password,
                'user.confirm': password,
>               'roles.resources.assigned': ROLES,
            })
```

```
2018-08-21 15:31:52 - widgetastic_null - ERROR - [UserCreateView/roles/resources/filter]: An exception happened during fill('Boot disk access') call (elapsed 17098 ms)
2018-08-21 15:31:52 - widgetastic_null - ERROR - [UserCreateView/roles/resources/filter]: Message: Unexpected server error.
```

**Comment by jhutar** [comment]
First, I consider a bug that AirGun (or Widgetastic or ... ?) reports some error with this generic text. Second, the test should not fail (but maybe it is failing because of product bug...) :-)

**Comment by jhutar** [comment]
These tests are failing with same error:

* tests.foreman.ui_airgun.test_contentview::test_positive_repo_count_for_composite_cv
* tests.foreman.ui_airgun.test_location::test_positive_update_compresource
* tests.foreman.ui_airgun.test_organization::test_positive_update_media
* tests.foreman.ui_airgun.test_organization::test_positive_update_ptable with
* tests.foreman.ui_airgun.test_location::test_positive_update_user with
* tests.foreman.ui_airgun.test_organization::test_positive_update_environment with
* tests.foreman.ui_airgun.test_organization::test_positive_update_hostgroup with
* tests.foreman.ui_airgun.test_user::test_positive_create_with_all_roles with
* tests.foreman.ui_airgun.test_user::test_positive_create_with_multiple_roles with
* tests.foreman.ui_airgun.test_usergroup::test_positive_delete_with_user with
* tests.foreman.ui_airgun.test_contentview::test_positive_publish_composite_with_custom_content

**Comment by abalakh** [comment]
Doesn't happen anymore and mentioned tests are passing. Maybe it was infra/product issue.
