### ISSUE TITLE
Vertical navigation doesn't work in 6.5

### ISSUE THREAD

**Issue by lhellebr** [SatelliteQE/airgun#235]
Due to this BZ ( https://bugzilla.redhat.com/show_bug.cgi?id=1647482 ), Vertical navigation doesn't work because there are IDs missing. This makes most tests fail.
I'm opening an issue here so we can track it but I prefer not fixing it in Airgun. I'm going to push developers to fix the BZ ASAP.

**Comment by ldjebran** [comment]
This is fixed in https://github.com/SatelliteQE/airgun/pull/233

**Comment by lhellebr** [comment]
Nice, but please note that the BZ is probably going to be fixed soon.

**Comment by abalakh** [comment]
Fixed in #236 which was risen to solve this ASAP. The fix will work OK for now and when id is returned back.
