### ISSUE TITLE
job template inputs moved from button to new tab

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/airgun#269]
Test `tests/foreman/ui_airgun/test_jobinvocation.py::test_positive_run_custom_job_template_by_ip` attempts to fill `job.template_input.input_type`, but that fails with:
```
> raise NoSuchElementException('Could not find an element {}'.format(repr(locator)))
E selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator="//div[contains(@class, 'template_inputs')]/following-sibling::div[1]")
```
It is because job template inputs were moved to extra tab now [compared to button in 6.4 and older (?) 6.5 snaps].

**Comment by jhutar** [comment]
Hello @ldjebran . 6 days ago your commits were merged:

https://github.com/SatelliteQE/airgun/commit/3a55dae181dd8e0b9aa6451326e0457f6cfa97ef
https://github.com/SatelliteQE/airgun/commit/51f05056202fa25744a39891a5daacc48c015f6f

Are these related to this? In latest snap, I have seen improvement. Job template gets created, but then it fails with:

```
                session.jobinvocation.run({
                    'job_category': 'Miscellaneous',
                    'job_template': job_template_name,
                    'search_query': 'name ^ {}'.format(hostname),
> 'template_content.command': 'ls',
                })
```

**Comment by oshtaier** [comment]
Yeah, these commits resolved mentioned issue
