### ISSUE TITLE
Audit entity

### ISSUE THREAD

**Issue by lhellebr** [SatelliteQE/airgun#302]
Me and rplevka want to add Audit entity (you can find Audit in Monitoring submenu). Audit is a feature that is not new but hasn't been automated in WebUI yet.
Audit uses interface that can't IMO be fully implemented by using existing widgets, mainly because there is no details page: instead, the entries are opened in the entry list itself upon clicking an entry. We are thinking about creating a new widget based on SatTable. Any suggestions before we start our work?

**Comment by oshtaier** [comment]
Sounds good. You will need to create custom, read only view for audit entity (entity/audit.py). Something like this (just an idea):

```
class AuditEntry(View):
    user = Text('.//a[@title='Filter audits for this user only']')
    operation_done = Text...
    entity_type = Text...
    entity_name = ...
    expander = Text(".//div[@class='list-view-pf-expand'")
    affected_org = Text...
    affected_loc = ...
    summary_table = Table(.//...)

    def __init__(self, parent, logger=None):
        View.__init__(self, parent, logger=logger)
         if 'active' not in self.browser.classes(self.expander):
             self.expander.click()
             self.browser.wait_for_element(self.affected_org, visible=True)

    def filter(...)
        self.user.click()

    def fill()
        raise()
```

**Comment by oshtaier** [comment]
and do not forget that `SatTable` is deprecated and should not be used

**Comment by abalakh** [comment]
>the entries are opened in the entry list itself upon clicking an entry.

That sounds like Expandable/Collapsible Table from patternfly4:
http://patternfly-react.surge.sh/patternfly-4/components/table

Is that your case? We can wait for https://github.com/quarckster/widgetastic.patternfly4/pull/11 and use it then

**Comment by oshtaier** [comment]
Yeah, part of this can be re-used, but still we need to specify that custom view

**Comment by oshtaier** [comment]
Starting look on that task by myself
@abalakh Analyzed more, both https://github.com/quarckster/widgetastic.patternfly4/pull/11/files and our UI. We have no table, tr, th, td and etc, so it is impossible to re-use mentioned code even if we rewrite all locators, because we cannot operate with any logical term specific to table in absence of it

**Comment by oshtaier** [comment]
Resolved in https://github.com/SatelliteQE/airgun/pull/319

**Comment by lhellebr** [comment]
Thank you a lot, @oshtaier !

**Comment by oshtaier** [comment]
sure, no problem
