### ISSUE TITLE
create_fake_host broken

### ISSUE THREAD

**Issue by lhellebr** [SatelliteQE/airgun#336]
``E ValueError: Could not find a corresponding registered view.`` where the view is supposed to be ``provider_content``.

It probably got broken by this PR: https://github.com/SatelliteQE/airgun/pull/327

**Comment by oshtaier** [comment]
of course, it is not that method broken, but there is a chance we have issue here. What test did produce the error?

**Comment by oshtaier** [comment]
Yes, there is issue present, but how do you get that particular exception?

**Comment by lhellebr** [comment]
I reproduced by running my not-yet-merged reporting tests AND by running``tests/foreman/ui/test_host.py::test_positive_create``.

**Comment by oshtaier** [comment]
hmm, It should fail on `test_positive_read_from_edit_page`, but I cannot understand way it fail on a first one, especially in that way. Anyway, we have regression here. Thanks.

**Comment by lhellebr** [comment]
I think it happens because the tab is not decorated as ``@View.nested`` anymore

**Comment by oshtaier** [comment]
that happened because `Deploy On` field is not there when you read entity back. And that is expected, we just do not handle it at all.
As I said, we can't have problem with create procedure except situation when you provide unknown provider to the framework, but that is not bug, but extra effort.
