### ISSUE TITLE
Add label DO NOT MERGE and WIP in airgun.

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/airgun#374]
I do not see `DO NOT MERGE` and `WIP` labels in airgun. 
@omkarkhatavkar @vijay8451 @mirzal is it ok to add these labels?

**Comment by mirzal** [comment]
Added "DO NOT MERGE".

Do you think we need both "DO NOT MERGE" and "WIP"?

**Comment by omkarkhatavkar** [comment]
good to have both

**Comment by vijay8451** [comment]
@mirzal thanks , it's would be a plus to add `WIP` too ..sometime things takes time to complete over PR with another work.

**Comment by mirzal** [comment]
Hmm... looks like we do not have "WIP" / "Work in Progress" in Nailgun or Robottelo.

For me, "DO NOT MERGE" includes "WIP". "WIP" means "do not merge it, I'm still working on that". "DO NOT MERGE" has the same effect, but doesn't go into causes - maybe I'm still working on that, maybe we need another PR merged first, maybe it conflicts with another PR and we need to figure out merge order.

Am I missing something?

**Comment by vijay8451** [comment]
Ah .. in robottelo we have `In Progress` instead of `WIP`  and seen uses of it in below ways ..

"DO NOT MERGE" => as depended PR is pending to merge
"IN Progress" => Not requires a review as author of PR still working on it.

**Comment by mirzal** [comment]
Added "In progress" label.

Closing the issue now, thanks for your explanations.
