### ISSUE TITLE
In RTD docs, API -> Entities and API -> Views containes only class names, not a docstrings

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/airgun#38]
Check:

https://airgun.readthedocs.io/en/latest/api/airgun.entities.html
https://airgun.readthedocs.io/en/latest/api/airgun.views.html

and compare to e.g.:

https://airgun.readthedocs.io/en/latest/api/airgun.browser.html

**Comment by abalakh** [comment]
That's no surprise as mentioned modules contain no docstrings as of now 🙂

**Comment by jhutar** [comment]
Hehe, I was pretty sure I was getting some texts there before. Cool :)

**Comment by mirzal** [comment]
Actually, neither of linked URL displays classes, methods or their docstrings. Current API documentation seems to be completely broken.

I'm closing this at the expense of broader #354 . We need systemic solution here.
