### ISSUE TITLE
Previous search text doesn't get cleared while performing next search in UI tests.

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/airgun#382]
When we perform first search using `session.something.search` and again perform another search for same entity/page then the new search text gets appended on previously searched text.
Some tests are failing because of this behaviour. How can I prevent this from happening in my test and is this a valid airgun issue?

**Comment by vijay8451** [comment]
@jameerpathan111 this issue more looks related to chrome driver itself  for more details refer https://github.com/SatelliteQE/airgun/issues/249

**Comment by mirzal** [comment]
Yes, this is already reported as #249. There is nothing you can do, unless you want to dig into this issue and try to fix it (is it really caused by Chromedriver? Can it be worked around?).
