### ISSUE TITLE
host collection delete fails to confirm removal in the popup window

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/airgun#392]
Manifestes in tests/foreman/ui/test_hostcollection.py::test_positive_end_to_end as

**Comment by omkarkhatavkar** [comment]
@pondrejk if this issue fixed, can we close this issue?

**Comment by pondrejk** [comment]
@omkarkhatavkar I didn't work on this issue, the pr above mentions it only as a reason for one test failure. Though I see the test is now passing consistently
