### ISSUE TITLE
unpin widgettastic/navmazing

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [SatelliteQE/airgun#393]
pinning navmazing/widgettastic to very exact versions makes airgun incompatible with the rest of the ecosystem as it always requests that specific version

please use less specific pins or at last minimal version pins

**Comment by mirzal** [comment]
Sorry for late reply, I was on PTO.

I take that you mean "inconsistent"? Using specific, old version may put us in unsupported territory, with all consequences of that, but I don't see how it may make Airgun incompatible.

What are navmazing/widgetastic backwards stability promises? Are they documented anywhere?

Overall, I prefer us to diverge from upstream as little as possible, so thanks for pointing out this issue. I will run our UI tests with unpinned dependencies to assess impact of freeing them. Nonetheless, we have just released Satellite 6.6 Beta, expect GA in next couple of months, we are in the middle of UI tests stabilization initiative and might move from Saucelabs to Zalenium soon. With all that, I would prefer to not add another potentially breaking change to the mix. I believe right time for freeing dependencies version will be right after Sat 6.6 GA.

**Comment by RonnyPfannschmidt** [comment]
Key problem is that if airgun comes in as a dependency it currently forces pip to get a really old version of widgetastic, more details when I'm back from pto

**Comment by mirzal** [comment]
I finally have results from Satellite QE automation run when Airgun dependencies are not pinned.

1. Logging changes in navmazing 1.1.6 prevents Airgun from starting up with following error:
```
../../shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/lib64/python3.6/copy.py:150: in deepcopy
    y = copier(x, memo)
../../shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/lib64/python3.6/copy.py:240: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                    else:
                        reductor = getattr(x, "__reduce_ex__", None)
                        if reductor:
>                           rv = reductor(4)
E                           TypeError: can't pickle _thread.RLock objects
```
Root cause is line: https://github.com/SatelliteQE/airgun/blob/master/airgun/session.py#L185

2. With above issue fixed (by forcing navmazing 1.1.5), I got 63 tests failed, as opposed to 62 failed in last normal automation run (both out of 420). However, 33 failed in unpinned run did pass in usual pinned run. I believe these differences has more to do with stability of our automation and intermittent infrastructure problems. Nevertheless, some are probably genuine regressions that will require additional work on our side.

**Comment by mirzal** [comment]
@omkarkhatavkar @latran @lhellebr 
take a look at analysis above. If we unpin Airgun dependencies, we can expect up to 30 new tests failures. You think it's worth doing right now, or shall we wait for Satellite 6.6 GA?

**Comment by RonnyPfannschmidt** [comment]
why copy the navigator ?

**Comment by mirzal** [comment]
> why copy the navigator ?

That's question to @abalakh , he added this in c12a9a74

**Comment by RonnyPfannschmidt** [comment]
i do wonder if a more matching/intended integration is sensible doable

**Comment by abalakh** [comment]
@RonnyPfannschmidt @mirzal re deepcopy - the idea was to have each session object completely isolated from each other, as it has separate browser instance and separate entities. deepcopy was used to avoid recalculating entire tree of paths, as at that moment resulting object was simple and could easily be copied. If it's not the case anymore - then maybe we should sacrifice that isolation. I can remember any real benefits from it, just ideological one.

**Comment by RonnyPfannschmidt** [comment]
The navigation content was supposed to be reasonable to be a global, as the detail data comes from navigation targets

**Comment by vijay8451** [comment]
> @omkarkhatavkar @latran @lhellebr @vijay8451
> take a look at analysis above. If we unpin Airgun dependencies, we can expect up to 30 new tests failures. You think it's worth doing right now, or shall we wait for Satellite 6.6 GA?

As per my understanding , we defiantly should wait till GA release and then give a try to new snap using unpin version as that would give:
- Some buffer time to play with it (without much current impact)
- Allow us to improve automation if require or may ask to devs too if requires improvement at product end too.

**Comment by omkarkhatavkar** [comment]
@mirzal I kind agree with Vijay as we can wait till Satellite 6.6 GA release.

**Comment by ldjebran** [comment]
@RonnyPfannschmidt @mirzal  how about unpin the versions from airgun and pin them in robottelo it self.

**Comment by ldjebran** [comment]
@omkarkhatavkar ^

**Comment by mirzal** [comment]
@ldjebran that will work for me. Submitted https://github.com/SatelliteQE/robottelo/pull/7357 . Let's see what rest of the team has to say.

**Comment by ldjebran** [comment]
@mirzal many thanks.
