### ISSUE TITLE
Branching 6.6

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/airgun#412]
Satellite 6.6 was released recently, to it's time to create branch 6.6.z and let master work towards 6.7.

If nobody expresses any veto in next ~24 hours, I'm going to create new branch.

@omkarkhatavkar @vijay8451 @lhellebr @latran

**Comment by omkarkhatavkar** [comment]
@mirekdlugosz :+1:

**Comment by vijay8451** [comment]
Good to move further :+1:

**Comment by mirekdlugosz** [comment]
Branch 6.6.z has been created. Of course there is no difference compared to master right now.
From now on, master is work towards 6.7. If any change is needed for both 6.6 and 6.7, it should be submitted against master and cherry-picked later. If something is needed only for 6.6, it should be submitted against 6.6.z.
