### ISSUE TITLE
Job template edit view is changed in Sat 6.7

### ISSUE THREAD

**Issue by peterdragun** [SatelliteQE/airgun#425]
Editor field in template edit view has lot of changes. Looks like change needs to be done [here](https://github.com/SatelliteQE/airgun/blob/master/airgun/views/common.py#L377). And there is also new field 'Description' below editor field.
old:
![image](https://user-images.githubusercontent.com/43444182/69059182-54b59a00-0a15-11ea-892a-047b8c6ecb22.png)

new:
![image](https://user-images.githubusercontent.com/43444182/69059147-42d3f700-0a15-11ea-9347-6a3d12f4beb0.png)

**Comment by mirekdlugosz** [comment]
Code pointers:
* In `airgun/views/common.py` there is `TemplateEditor` class that models editor and associated widgets
* editor itself is `ACEEditor` from `airgun/widgets.py`
* "Description" field should be added as normal field in `airgun/views/job_template.py` (it's not really part of UI associated with editor)
