### ISSUE TITLE
Add support for email functionality verification using SMTP/Sendmail delivery method.

### ISSUE THREAD

**Issue by devendra104** [SatelliteQE/airgun#476]
Planning to add the support of email functionality verification for both delivery method 
- Sendmail
- SMTP

To provide the support of send email and email notification verification, we will require to update the settings entities and their view module.

**Locator**
locator for email_button
```
email_button = Text('#test_mail_button')
notification_locator = Text('//*[@id="toast-notifications-container"]/div/div')
```
**method:**
To read the contents of settingsview, we will require a separate method 
 ```
def contents(self):
        view = SettingsView(self.browser)
        return view

```

**Comment by mshriver** [comment]
@devendra104 has this issue been resolved by the above linked PRs?

**Comment by devendra104** [comment]
@mshriver yes it has been resolved.
