### ISSUE TITLE
Implement proper am_i_here() for Edit*EntityName* NavigateStep 

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#63]
Currently NavigateSteps for navigating to entity edit page are only checking whether entity details view is open.
E.g. if you have activation keys `foo1`, `foo2`, have `foo1` details page opened and want to edit `foo2` - navigator will think that you're on `foo2` details page already, as it doesn't check specific entity name but just ensures any AK details page is opened.
The task will probably require adding `Breadcrumbs` patternfly widget.

**Comment by mshriver** [comment]
I think that the breadcrumb widget implemented in ManageIQ/integration_tests can be pulled into widgetastic_patternfly:
https://github.com/ManageIQ/integration_tests/blob/master/widgetastic_manageiq/__init__.py#L1717

**Comment by abalakh** [comment]
Successfully resolved in #92
