### ISSUE TITLE
Add test coverage for Domain entity

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#75]
Add views and entity for Domain:
![image](https://user-images.githubusercontent.com/10895065/39529725-0963748e-4e30-11e8-8368-1b502a7f7b60.png)

![image](https://user-images.githubusercontent.com/10895065/39529461-68559e78-4e2f-11e8-9f43-0c67645cfc20.png)

So correspondingly cover `Domain`, `Parameters`, `Organization` and `Location` tabs
Add `create`, `edit`, `read` and `delete` actions to entity
Refer to already implemented code for proper approach and issues https://github.com/SatelliteQE/airgun/issues/58 or https://github.com/SatelliteQE/airgun/issues/57 to get more idea on what things should be covered for each specific tab

**Comment by bsquizz** [comment]
I can start on this

**Comment by oshtaier** [comment]
Addressed in https://github.com/SatelliteQE/airgun/pull/87
