### ISSUE TITLE
Create test coverage for partition table entity

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#78]
Add necessary code for views and entities to cover:
![image](https://user-images.githubusercontent.com/10895065/39535521-c68378a0-4e3c-11e8-8304-d2526ecf23e7.png)
![image](https://user-images.githubusercontent.com/10895065/39535546-d93e382c-4e3c-11e8-9f31-a79270d1cf25.png)
Cover all widgets in `Template`, `Locations` and `Organizations` tabs. Verify that `Help` tab is not empty

ACE editor 
![image](https://user-images.githubusercontent.com/10895065/39535638-17664c3e-4e3d-11e8-8f77-18c3dfc8b04f.png)
is already has own custom widget implemented, so please reuse it

Look for tier2 tests in Robottelo and move all of them into new airgun folder using new framework

**Comment by tstrych** [comment]
@oshtaier @abalakh , I have some questions on you, hopefully you will help me.

where I can find some examples how should the Template can looks like ? (also diff preview, import fullscreen options and syntax highlighting of languages are going to be used ? )

The check-box Snippet will hide you Operating System family drop-down bar, in activation key you use LimitInput, but here it happens in opposite way, what widget class should I use and how to solve this problem ?

**Comment by oshtaier** [comment]
Do you mean `TemplateEditor` widget like here https://github.com/SatelliteQE/airgun/blob/master/airgun/views/template.py#L38 ?
That widget already should handle everything you mentioned. Of course, it was not tested much, but it should work

About second question. Huh. That is classical situation for `ConditionalSwitchableView` which was not used yet and now I am only trying to understand the logic (which is not complex so much) and implement at least one example. It should be one `Checkbox` which will be criteria for next field to be displayed. However not sure, how to trigger absence of the element. At least, you have place to start.

**Comment by oshtaier** [comment]
Addressed in https://github.com/SatelliteQE/airgun/pull/85
