### ISSUE TITLE
Add test coverage for user group entity

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#88]
Add necessary entity and views for User Group functionality(Administer->User Group):
* [x] All entities page
* [x] Create/Edit entity page
* [x] User Group Details - User Group tab
* [x] User Group Details - Roles tab
![image](https://user-images.githubusercontent.com/10895065/40131317-4cf38f6e-5942-11e8-90b1-bff669601fec.png)

**Comment by schlupov** [comment]
So can I start work on this issue?

**Comment by oshtaier** [comment]
once you done with previous task, sure, why not

**Comment by oshtaier** [comment]
however, maybe someone from CF team can pick up it

**Comment by schlupov** [comment]
I'll leave this issue for someone from CF team.

**Comment by oshtaier** [comment]
@mirzal What is your progress on the issue?
