### ISSUE TITLE
Create custom widgets specific to Satellite

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#9]
List of widgets that I am already classified:
- Classical select list in case we don't have it:
![image](https://user-images.githubusercontent.com/10895065/36453613-55755d7c-16a1-11e8-9b79-6b5e1ec52fd5.png)
- Select field with search:
![image](https://user-images.githubusercontent.com/10895065/36424936-c1253622-164d-11e8-801f-5b10d65a3e5b.png)
- Select field with inherit
![image](https://user-images.githubusercontent.com/10895065/36424809-5018c76e-164d-11e8-9e00-2b19879af232.png)
- Radio group
![image](https://user-images.githubusercontent.com/10895065/36480442-054696bc-1715-11e8-85b4-fba788641120.png)
- Name-Value parameter
![image](https://user-images.githubusercontent.com/10895065/36424850-7e7a15b8-164d-11e8-9bb5-4f9126c6995b.png)
- Matcher
![image](https://user-images.githubusercontent.com/10895065/36453578-333f7fda-16a1-11e8-89e4-50e5dfb1654f.png)
- ace editor
![image](https://user-images.githubusercontent.com/10895065/36479133-3395c52e-1710-11e8-8342-4ecda4f125c2.png)
- calendar
![image](https://user-images.githubusercontent.com/10895065/36482019-7c4d50f2-171a-11e8-912d-cce8481c16e1.png)
- Maybe paginator

**Comment by abalakh** [comment]
Pls note that in general a lot of satellite widgets are actually patternfly widgets (even entire tables with paginators), so we should take a look at widgetastic.patternfly before introducing new widgets.

**Comment by digitronik** [comment]
@abalakh @abalakh right, Most of the widget are from Patternfly.  Calendar widget[0] which is wapper on bootstrap DatePicker. Even we are trying to add it to widgetastic.patternfly[1].

[0] http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/
[1] https://github.com/RedHatQE/widgetastic.patternfly/pull/55

**Comment by abalakh** [comment]
Closing as all mentioned widgets and the rest required for tier2 tests are already implemented. If something new is found - feel free to open separate issue for new widget.
