### ISSUE TITLE
[Failed-AutoCherryPick] - Scap contentview title fixed

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/airgun#970]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.13.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/airgun/actions/runs/6158804531)
- [Parent Pull Request](https://github.com/SatelliteQE/airgun/pull/967)

**Comment by vijaysawant** [comment]
https://github.com/SatelliteQE/airgun/pull/968
